# Generated by Django 3.0 on 2019-12-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=100)),
                ('task_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
    ]
